name       : xdg-user-dirs-gtk
version    : '0.10'
release    : 5
source     :
    - https://download.gnome.org/sources/xdg-user-dirs-gtk/0.10/xdg-user-dirs-gtk-0.10.tar.xz : 739a1a89baf34aa7261e924a21d2ae646b0475b67b3db3daa84327a99132d83e
homepage   : http://www.gnome.org
license    :
    - GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Creates user dirs and asks to relocalize them
description: |
    Creates user dirs and asks to relocalize them
builddeps  :
    - pkgconfig(gtk+-3.0)
    - xdg-user-dirs
rundeps    :
    - xdg-user-dirs
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-MATE-support.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
