name       : xdg-user-dirs-gtk
version    : '0.11'
release    : 7
source     :
    - https://download.gnome.org/sources/xdg-user-dirs-gtk/0.11/xdg-user-dirs-gtk-0.11.tar.xz : 534bd563d3c0e3f8dcbf3578cb8ab0e49d3ba41c966d477c8af9438364121e7d
homepage   : http://www.gnome.org
license    :
    - GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Creates user dirs and asks to relocalize them
description: |
    Creates user dirs and asks to relocalize them
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gettext-devel
    - xdg-user-dirs
rundeps    :
    - xdg-user-dirs
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-MATE-support.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
